# -*- coding: utf-8 -*-
"""Sentiment_Analysis_Deploy.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EzESKx0t6h8GtPPj-iahspITIn_QeFqD
"""

#%% Deployment unusually done on PC/mobile phone

from tensorflow.keras.preprocessing.text import tokenizer_from_json
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.models import load_model
import numpy as np
import pickle
import json
import os
import re

#1) Trained model --> loading from .h5
#2) tokenizer --> loading from json
#3) MMS/OHE --> coming from pickle

TOKENIZER_PATH = os.path.join(os.getcwd(),'tokenizer_sentiment.json')
OHE_PATH = os.path.join(os.getcwd(),'ohe.pkl')

# to load trained data
loaded_model = load_model(os.path.join(os.getcwd(),'model.h5'))
loaded_model.summary()

# to load tokenizer
with open(TOKENIZER_PATH,'r') as json_file:
  loaded_tokenizer = json.load(json_file)

# to load ohe
with open(OHE_PATH,'rb') as file:
    loaded_ohe = pickle.load(file)

#%%
input_review = input('type your review here: ')

# preprocessing
input_review = re.sub('<.*?>',' ',input_review)
input_review = re.sub('[^a-zA-Z]',' ',input_review).lower().split()

tokenizer = tokenizer_from_json(loaded_tokenizer)
input_review_encoded = tokenizer.texts_to_sequences(input_review)

max_len = 180

input_review_encoded = pad_sequences(np.array(input_review_encoded).T,
                                     maxlen=max_len,
                                     padding='post',
                                     truncating='post')

outcome = loaded_model.predict(np.expand_dims(input_review_encoded,axis=-1))

print(loaded_ohe.inverse_transform(outcome))